#!/usr/bin/env python3
"""
Generates src/server/embedded_web_assets.cpp from web/dist/, embedding the
built frontend directly into the C++ server binary as byte arrays so the
compiled binary is genuinely self-contained -- no web/dist/ directory has
to travel with it at deploy time. Run before compiling (build.sh does this
automatically); re-run any time web/dist/ changes.

Not part of the shipped binary's runtime -- this is a build-time code
generator only, same category as running `vite build` itself.
"""
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST_DIR = os.path.join(REPO_ROOT, "web", "dist")
OUT_PATH = os.path.join(REPO_ROOT, "src", "server", "embedded_web_assets.cpp")


def sanitize_identifier(url_path: str) -> str:
    return "k_asset_" + re.sub(r"[^A-Za-z0-9]", "_", url_path)


def emit_byte_array(out, identifier: str, data: bytes) -> None:
    out.write(f"static const unsigned char {identifier}[] = {{\n")
    line = []
    for i, byte in enumerate(data):
        line.append(f"0x{byte:02x}")
        if len(line) == 20:
            out.write("  " + ",".join(line) + ",\n")
            line = []
    if line:
        out.write("  " + ",".join(line) + "\n")
    out.write("};\n")


def main() -> int:
    if not os.path.isdir(DIST_DIR):
        print(f"error: {DIST_DIR} does not exist -- run `npm run build` in web/ first", file=sys.stderr)
        return 1

    files = []
    for root, _dirs, filenames in os.walk(DIST_DIR):
        for filename in filenames:
            full_path = os.path.join(root, filename)
            url_path = "/" + os.path.relpath(full_path, DIST_DIR).replace(os.sep, "/")
            files.append((url_path, full_path))
    files.sort()

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as out:
        out.write("// AUTO-GENERATED by scripts/embed_web_assets.py from web/dist/ -- do not edit by hand.\n")
        out.write('#include "embedded_web_assets.h"\n')
        out.write("#include <unordered_map>\n\n")
        out.write("namespace {\n\n")

        entries = []
        total_bytes = 0
        for url_path, full_path in files:
            with open(full_path, "rb") as f:
                data = f.read()
            total_bytes += len(data)
            identifier = sanitize_identifier(url_path)
            emit_byte_array(out, identifier, data)
            out.write("\n")
            entries.append((url_path, identifier, len(data)))

        out.write("const std::unordered_map<std::string, EmbeddedAsset>& registry() {\n")
        out.write("  static const std::unordered_map<std::string, EmbeddedAsset> r = {\n")
        for url_path, identifier, size in entries:
            escaped = url_path.replace("\\", "\\\\").replace('"', '\\"')
            out.write(f'    {{"{escaped}", {{{identifier}, {size}}}}},\n')
        out.write("  };\n")
        out.write("  return r;\n")
        out.write("}\n\n")
        out.write("}  // namespace\n\n")
        out.write("const EmbeddedAsset* find_embedded_web_asset(const std::string& path) {\n")
        out.write("  const auto& r = registry();\n")
        out.write("  auto it = r.find(path);\n")
        out.write("  return it == r.end() ? nullptr : &it->second;\n")
        out.write("}\n")

    print(f"Embedded {len(entries)} file(s), {total_bytes} bytes total, into {os.path.relpath(OUT_PATH, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
